### ISSUE TITLE
Bettering your code...

### ISSUE THREAD

**Issue by ghost** [Nonemoticoner/braille#3]
I really liked your module but it contained repetitions and many _if_s and _for_ loops. I tried to improve it, so I edited it, and ended with a shorter, cleaner, faster version that I named [Br6.js](https://github.com/nikola-kamikazi/br6.js).

I wish you'd take a look at it (and why not update your code if you like what I did)

Peace <3

**Comment by Nonemoticoner** [comment]
Hi,
thanks for writing. This module is really old and I continue to postpone its rewrite for too long time.

I'm currently on holidays but once I'm back I'll see your code and will think about improvements ;)
